FROM ubuntu:22.04

RUN apt-get update && apt-get install -y ca-certificates && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY . .

RUN chmod +x Server.x86_64

ENTRYPOINT ["./Server.x86_64", "-batchmode", "-nographics"]
